on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/test-app
          tags: |
            type=semver,pattern={{version}}     

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push no tag
        id: notagiamge
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        id: tagiamge
        if: github.ref_name == 'tag'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Add kubeconfig
        uses: azure/k8s-set-context@v4
        with:
           method: kubeconfig
           kubeconfig: ${{ secrets.KUBE_CONFIg }}

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIg }}
        with:
          command: |
            helm version
            kubectl version
            kubectl cluster-info 
            helm upgrade app-nginx --install --wait --set image.tag=${{ steps.meta.outputs.tags }} 
